### PR TITLE
✨ Add Splash Screen

### LINKED ISSUE #1: Add Splash Screen
- [ ] Forward to second page after a few seconds
- [ ] Add logo
- [ ] Animate the three circles

### PR DESCRIPTION
**Pull request by lmachens**
Fixes #1

### CODE REVIEW

**Review by cboenke — CHANGES_REQUESTED** [review]
Increase font size

**Review by cboenke — APPROVED** [review]
LGTM

**Review by JuKahl — APPROVED** [review]

**Review by sweisz — APPROVED** [review]

**Review by RonjaMeinecke — APPROVED** [review]

**Review by ShiningElektra — APPROVED** [review]
GJ

**Review by mrana17 — APPROVED** [review]
gj 🚀

**Pull request merged**
